// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeqGIhvvPYTymmUSFoIZJNwFBa8nqC6go',
    appId: '1:416315033087:web:6cf0954344bef15e4d13ca',
    messagingSenderId: '416315033087',
    projectId: 'lib-dart',
    authDomain: 'lib-dart.firebaseapp.com',
    databaseURL: 'https://lib-dart-default-rtdb.firebaseio.com',
    storageBucket: 'lib-dart.appspot.com',
    measurementId: 'G-LG236E1PER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAQqnz1-LA8tpmqLJOPCShDN2mC-Ra4X0',
    appId: '1:416315033087:android:b8c1cfc0f725bb9d4d13ca',
    messagingSenderId: '416315033087',
    projectId: 'lib-dart',
    databaseURL: 'https://lib-dart-default-rtdb.firebaseio.com',
    storageBucket: 'lib-dart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnsH2gHpsIIrRxjfmSedpDhGrLermx-pY',
    appId: '1:416315033087:ios:b5137003f63782b54d13ca',
    messagingSenderId: '416315033087',
    projectId: 'lib-dart',
    databaseURL: 'https://lib-dart-default-rtdb.firebaseio.com',
    storageBucket: 'lib-dart.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnsH2gHpsIIrRxjfmSedpDhGrLermx-pY',
    appId: '1:416315033087:ios:b5137003f63782b54d13ca',
    messagingSenderId: '416315033087',
    projectId: 'lib-dart',
    databaseURL: 'https://lib-dart-default-rtdb.firebaseio.com',
    storageBucket: 'lib-dart.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeqGIhvvPYTymmUSFoIZJNwFBa8nqC6go',
    appId: '1:416315033087:web:a64a5ade5a3b1c1a4d13ca',
    messagingSenderId: '416315033087',
    projectId: 'lib-dart',
    authDomain: 'lib-dart.firebaseapp.com',
    databaseURL: 'https://lib-dart-default-rtdb.firebaseio.com',
    storageBucket: 'lib-dart.appspot.com',
    measurementId: 'G-8JGLDRTNL3',
  );
}
